### ISSUE TITLE
MenuTreeFor for all pages

### ISSUE THREAD

**Issue by Matthew-Bonner** [KalikoCMS/KalikoCMS.Core#134]
I tried to use KalikoCMS.Mvc.Extensions.MenuTreeFor with both the start page and root of the site like so:

`Html.MenuTreeFor(Model.CurrentPage, PageFactory.GetPage(Model.CurrentPage.RootId)`
`Html.MenuTreeFor(Model.CurrentPage, PageFactory.GetPage(SiteSettings.RootPage)`
`Html.MenuTreeFor(Model.CurrentPage, PageFactory.GetPage(SiteSettings.Instance.StartPageId)`

The following shows the outline of the pages I've created so far:
![wiki tree](https://user-images.githubusercontent.com/7858744/31006747-f0c69e8a-a4f5-11e7-8263-63b4caa63a76.PNG)

The Homepage is set as the start page.

The tree is always empty because the start page has no children and the function does not recognise that when passing the root id I actually want a tree of all pages in the site.

Is there a way around this or do I need to write my own MenuForTree.

I don't want to add all pages under the Homepage because I use the structure to output links for the navbar.

**Comment by fschultz** [comment]
`Html.MenuTreeFor(Model.CurrentPage, PageFactory.GetPage(SiteSettings.RootPage)` should be able to do that but a bug in the root page is currently stopping the rendering.

This is due to the root page falsely telling the extension that it doesn't have any pages under it and therefor the menu tree isn't rendered. I'm adding this as a bug to be fixed in the next release since the root page should be aware of any pages.

As a work-around before the next version you could either duplicate the [MenuTreeFor extension](https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Mvc/Extensions/HtmlHelperExtensions.cs) and remove the following:
```
            if (!rootPage.HasChildren) {
                return null;
            }
```

Or use a helper such as:
```
@helper RenderTree(CmsPage page) {
    <ul class="nav nav-pills nav-stacked">
        @foreach (CmsPage child in page.Children)
        {
            // Don't show pages that isn't visible in menus
            if (!child.VisibleInMenu)
            {
                continue;
            }
            <li class="@(Model.CurrentPage.PageId == child.PageId ? "active" : "")">
                <a href="@child.PageUrl">@child.PageName</a>
                @if (child.HasChildren && (Model.CurrentPage.ParentPath.Contains(child.PageId) || Model.CurrentPage.PageId == child.PageId))
                {
                    // Only expand selected node
                    @RenderTree(child)
                }
            </li>
        }
    </ul>
}
```

**Comment by Matthew-Bonner** [comment]
Tried your solution and it works, thanks.
