### ISSUE TITLE
Error In Building Source Code

### ISSUE THREAD

**Issue by mikrokode** [KalikoCMS/KalikoCMS.Core#155]
System.ArgumentException: 'No Backend was specified for the connection string name 'KalikoCMS'. It is recommended to use connection string names and entries in the configuration file.'

**Comment by mikrokode** [comment]
Another error;

System.NullReferenceException: 'Type.GetType(KalikoCMS.Search.KalikoSearchProvider, KalikoCMS.Search) returned null.'

**Comment by fschultz** [comment]
Hi,
Could you tell me a little bit on how you're running the project?

The easiest way to get up and running with the CMS is to [install it through NuGet](https://github.com/KalikoCMS/KalikoCMS.Core#install-via-nuget). 

If you want to manually set it up from the source code you need to manually make the transformations (.install.xdt) to you web configuration that the packages otherwise does automatically, for instance using [SQL Server](https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Data.SqlServer/web.config.install.xdt) or [SQLite](https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Data.SQLite/web.config.install.xdt) (which are the cause of your first error) as well as the basic [siteSettings](https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Admin/web.config.install.xdt) (you seem to have the searchProvider attribute set but no referencing the [search provider assembly](https://github.com/KalikoCMS/KalikoCMS.Search) in your second error). Make sure to only apply the transformations to your web project and not any of the pre-made configs of the projects. (I would recommend using the NuGets for setting up the project which is far easier, and then if you prefer switch the references to the source projects).

I would also recommend looking at the [demo project](https://github.com/KalikoCMS/DemoSite.Mvc) for more information.

Hope this helps!
