### ISSUE TITLE
Role manager > Admin.Templates.MasterPages.Admin

### ISSUE THREAD

**Issue by usigirci** [KalikoCMS/KalikoCMS.Core#161]
Hi,
I want to make some rules for role management; but when I create a .cs file for MasterPages.Admin, the error occurs.
How can I do it?

**Comment by fschultz** [comment]
Hi,
Could you provide the error message as well as the .cs class (through https://kaliko.com/support/ if you don't want to post them here)? Thanks!

**Comment by usigirci** [comment]
Hello,

Thank you for your reply.

I started on the RoleManager reviews through the demo project at the
beginning of the project, but clearly then the topic changed according to
the needs of the designer, for example I am trying to find out how to
upload a ".svg" file now, because when i upload .svg it gives a .net error.

When I start working on the Role Manager, I will give information again.

Happy new year to you.

Umit.



Fredrik Schultz <notifications@github.com>, 31 Ara 2019 Sal, 14:05
tarihinde şunu yazdı:

**Comment by usigirci** [comment]
Hello,
I think i made a mistake, because some .cs files are missing.
Previously, I need Admin.Master.cs on the role manager.
How do I import missing .cs files?

And, can I use a svg file ImageLibrary? It can upload, but not added to the
page.

Can you help me please?

Best regards,
Umit.



Fredrik Schultz <notifications@github.com>, 31 Ara 2019 Sal, 14:05
tarihinde şunu yazdı:

**Comment by fschultz** [comment]
Best wishes for the new year!

Are you creating a new admin page for the role manager or are you looking to replace present functionality?

The ImageProperty type that uses ImageLibrary works on bitmap images to offer scaling. If you want to be able to use both svg and bitmap formats and don't require scaling (in other words, bitmap images will be provided in the correct format when uploading) you could switch to a FileProperty instead. It's very similar in upload functionality but lacks the image handling functions / size awareness.

If you need scaling I could help by looking how to create a image property type that could handle both svg and bitmap in the same time.

Best regards,
Fredrik

**Comment by usigirci** [comment]
Hello Mr. Schultz,
Thank you for your answer.

 Are you creating a new admin page for the role manager or are you looking
> to replace present functionality?


I want to define a new role, for example "editor" and this role should be
able to modify existing pages without creating a new page. I could not see
this feature in the available role management functions.


.. FileProperty instead. It's very similar in upload functionality but
> lacks the image handling functions / size awareness.


Thanks for the FileProperty proposal, it could work because we don't need
scaling.
However, the problem is that the uploaded image does not have a thumbnail
preview. I also couldn't show a preview when selecting from the visual
library.
Is it possible to see a preview when selecting files from the visual
library (instead of file name)?


I would like to proceed with Kaliko but I am looking for a solution for new
requests.
Thank you for giving a time.

Best regards,

Umit.




Fredrik Schultz <notifications@github.com>, 7 Oca 2020 Sal, 22:12 tarihinde
şunu yazdı:

**Comment by fschultz** [comment]
The ability to limit page creation based on roles is a feature that I think would be beneficiary to add to the CMS core, so that a developer could add limitations on a page type basis using a simple attribute decoration when defining the page types.

I'm thinking something in the line of:
```
    [PageType("ListPage", "List page", ...)]
    [CreateAccess("TheAdminGroup")]
    public class ListPage : CmsPage, IIndexable {
      ..
    }
```

This should be pretty straight forward to implement and I could probably have a beta ready in a not too distant future.

Regarding the image property; this could be solved by creating a custom property type based on ImageProperty. That way you can gain control over how the editor looks and acts. If you want I could help you by setting up the necessary files that you then can add to your project and modify as needed?

**Comment by usigirci** [comment]
Hello Mr.Schultz

Thank you for answers and kind help offer.
How can it be; for example, can you share a package that you have prepared
for similar situations?

Umit.


Fredrik Schultz <notifications@github.com>, 8 Oca 2020 Çar, 21:27 tarihinde
şunu yazdı:

**Comment by usigirci** [comment]
Hi,

We need to open the project for beta testing in the next few days, maybe if
you are going to release a development package during this time it will be
useful.
Would you recommend we wait?

Best regards,
Umit



Fredrik Schultz <notifications@github.com>, 8 Oca 2020 Çar, 21:27 tarihinde
şunu yazdı:

**Comment by fschultz** [comment]
I've scheduled time for development this weekend, so there should be a new pre-release with the role attribute out in a few days time. I will publish it as a beta on nuget.org and notify in this issue when it's available.

With the custom image property type I will provide the necessary files needed so that you can just add them to your project and customize.

**Comment by fschultz** [comment]
I've just published a new pre-release at https://www.nuget.org/packages/KalikoCMS.Core/1.2.6-beta1

It includes an optional parameter to limit access to page creation on a page type basis by specifying the new `CanCreate` parameter with one or more roles in the PageTypeAttribute.

```
    [PageType("SearchPage", "Search page", PageTypeDescription = "Used for search page", PreviewImage = "/Assets/Images/searchpage.png", CanCreate = new [] { "WebAdmin" })]
    public class SearchPage : CmsPage {
        ...
    }
```

With the code above only users in the WebAdmin role can create pages of the SearchPage type.

Page types that doesn't define `CanCreate` is available to all users with access to the CMS administration.

**Comment by fschultz** [comment]
I've created a package for you with a custom image property type and the necessary files for administration:
[CustomImagePropertyType.zip](https://github.com/KalikoCMS/KalikoCMS.Core/files/4081639/CustomImagePropertyType.zip)

Add the CustomPropertyType folder to your web project and optionally correct the namespaces (if you place it anywhere else please make sure to also update any paths for scripts etc.).

Add a new property to one of the page types with the new CustomImageProperty:
```
        [Property("Custom image")]
        public virtual CustomImageProperty MainImage { get; set; }
```

(I would recommend using new property names for the images (not reusing ImageProperty names) to avoid data incompatibility with already existing data)

I've modified the editor to work with .svg files as well as showing thumbnails in the file listing.

Please feel free to make further modifications so that it looks/works as you want.

Entry points for modification:
- CustomSelectFileDialog.aspx for any changes to the file browser
- CustomImagePropertyType.cs property rendering
- CustomEditImageDialog.aspx image editor/cropper
- CustomImagePropertyEditor.js preview image handling of not yet saved properties
- CustomImagePropertyEditor.ascx.cs preview image handling of saved properties

This is based on legacy code and thus a bit outdated unfortunately. The next generation of this CMS currently being worked on will have a brand new UI that will make these kind of things easier to work with.

**Comment by usigirci** [comment]
I installed the 1.2.6-beta1 package and i used the CanCreate feature, thank you.
_In the following days it would be beneficial to develop a solution for "Delete Pages". In CMS all of the user roles should not be able to delete pages. I made an arrangement with Html / Javascript on my project, but of course it is not a safe method._

**Comment by usigirci** [comment]
I used CustomImagePropertyType properties; it's very useful, thank you.

**Comment by usigirci** [comment]
> I've created a package for you with a custom image property type and the necessary files for administration:
> [CustomImagePropertyType.zip](https://github.com/KalikoCMS/KalikoCMS.Core/files/4081639/CustomImagePropertyType.zip)
> 
> Add the CustomPropertyType folder to your web project and optionally correct the namespaces (if you place it anywhere else please make sure to also update any paths for scripts etc.).
> 
> Add a new property to one of the page types with the new CustomImageProperty:
> 
> ```
>         [Property("Custom image")]
>         public virtual CustomImageProperty MainImage { get; set; }
> ```
> 
> (I would recommend using new property names for the images (not reusing ImageProperty names) to avoid data incompatibility with already existing data)
> 
> I've modified the editor to work with .svg files as well as showing thumbnails in the file listing.
> 
> Please feel free to make further modifications so that it looks/works as you want.
> 
> Entry points for modification:
> 
> * CustomSelectFileDialog.aspx for any changes to the file browser
> * CustomImagePropertyType.cs property rendering
> * CustomEditImageDialog.aspx image editor/cropper
> * CustomImagePropertyEditor.js preview image handling of not yet saved properties
> * CustomImagePropertyEditor.ascx.cs preview image handling of saved properties
> 
> This is based on legacy code and thus a bit outdated unfortunately. The next generation of this CMS currently being worked on will have a brand new UI that will make these kind of things easier to work with.

**Comment by usigirci** [comment]
CustomImageProperty needs to improve HtmlEditor.
When "Insert / Edit Image" is click in the HtmlEditor;
- Thumbnails don't seeing in the media library.
- Svg files not choose, uploaded by CustomImageProperty.

Can "Insert / Edit CustomImageProperty" such as "Insert / Edit Image" be added on "HtmlEditor", or can CustomImageProperty be default image property for HtmlEditor?

**Comment by fschultz** [comment]
If you have at least one CustomImageProperty on the page you're editing you could append the following code to CustomImagePropertyEditor.js:
```
$(document).ready(function() {
    top.propertyEditor.dialogs.openEditImageDialog = top.propertyEditor.dialogs.openEditCustomImageDialog;
});
```
This will rewire the dialog for the original image editor to instead use the custom one, so that when you're working with images in the HTML-editor the custom dialog will open instead.

If you don't have an CustomImageProperty on all pages that has an HtmlProperty you'll need to insert the modified CustomImagePropertyEditor.js some other way, for instance by creating a hidden property type that only register the script.
