### ISSUE TITLE
SearchProviderBase - IndexPage()

### ISSUE THREAD

**Issue by EdSF** [KalikoCMS/KalikoCMS.Core#45]
Just synced latest code and I'm hitting an odd `NullReferenceException` on `IndexPage(CmsPage page)` method.

I can see that the `page` param is in fact `null`. I can't seem to track this down at the moment...

How to repro:
- This exception is hit when creating a page.
- It occurs regardless if the page implements `IIndexable` or not
- Occurs on `Publish` and `Save Working Copy`

Now the "odd" part:
- The page is in fact created and persisted in DB `PageInstance` table
- It is however _not_ visible in Dashboard
- The only way to see in dashboard is to _restart/recycle_ the application (browser refresh or login/out has no effect)
- After the _restart/reclycle_, the Page is visible in Dashboard and is in "Unpublished" state
- You can Publish at that point and all's well
- This exception doesn't seem to affect the Indexing - you can go to _Search Engine -> Reindex website_ and the pages reported in the dashboard as indexed (correct number of pages)

This doesn't manifest in an "older" site (Nuget only code base)....

I'll continue tinkering and see if I can get somewhere....

**Comment by fschultz** [comment]
I'll try to see if I can recreate the problem. What version of KalikoSearch do you have?

**Comment by EdSF** [comment]
Ah...the "original" Nuget - `KalikoCMS.Search" version="0.9.8"`...

I can see it was updated 6/14 and I don't have that project synced. I'll see if doing so resolves this and will report back (though that will probably be later in the day). Thank you!

**Comment by fschultz** [comment]
Updating to https://www.nuget.org/packages/KalikoCMS.Search/1.0.0-beta (or https://github.com/KalikoCMS/KalikoCMS.Search/tree/3.0.3.4-dev) would hopefully solve the issue. The main change in KalikoSearch in the 1.0.0-beta-version is that instead of the previously used `PageSaved` event it now attaches itself to the new `PagePublished` event. But the event handler should still get a valid page - even if it listens to the "wrong" event - so I will still be looking into why it gets a `NullReferenceException`.

That the save/publish function halts on an error that occurs in event handlers is really bad and I will be sure to fix it before getting beta3 up. I'm really grateful that you found this error so that it can be fixed!

**Comment by EdSF** [comment]
I think all of us using KalikoCMS owe YOU for the great work! 

On a personal note, I want this project to do great things so while I'm currently really a n00b with this project, I will try to help :) Maybe at some point, when I get more core familiarity, I can do more than just break things :)

**Comment by fschultz** [comment]
Thank you! Really made my day :) Any contribution is always much appreciated.
