### ISSUE TITLE
Attribute routing?

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#62]
Hi I was wondering how to go about using attribute routing.
Basically I have tagged my articles and would like to have this route:

/tag/abc
/tag/xyz
Where abc and xyz are the tag names.

I tried [Route("Tags/{id}")] but it will only work if I do /tag/index/xyz, I would like to have it without the index if possible. 

This does work
 routes.MapRoute(
                name: "TagsDefault",
                url: "tags/{id}",
                defaults: new { controller = "Tags", action = "Index", id = UrlParameter.Optional }
            );

Also I am getting the list of articles by tags using the following query is this how you would go about it:
 var model =
                PageFactory.GetPages(pageType.PageTypeId)
                    .Select(x => x.ConvertToTypedPage<ArticlePage>())
                    .Where(x => x.Tags.Tags.Contains(id));

**Comment by fschultz** [comment]
The system should not interfere with the routing, so anything that would work in a clean MVC project should also work together with the CMS. Your example should work (just ensure that you have routes.MapMvcAttributeRoutes() called in the RouteConfig).

Something that I otherwise tend to do for tag lists is to extend the page type and re-route to the correct view if for instance url-to-my-blog-list/tag/xyz is requested.
```
    public class BlogHolderPageType : CmsPage, IPageExtender {

        public bool HandleRequest(Guid pageId, string[] remainingSegments) {
            if (remainingSegments.Length == 2 && remainingSegments[0] == "tag") {
                var page = PageFactory.GetPage(pageId);
                var additionalRouteData = new Dictionary<string, object> {{"tag", remainingSegments[0]}};

                RouteUtils.RedirectToController(page, "tag", additionalRouteData);
                return true;
            }
            return false;
        }
    }
```
This is would call the action Tag on the PageController for the blog holder page type with tag as a parameter.

(I'm a little bit unsure if this works for the start page without specifying it's URL segment in the address however.)

If you need to filter out a specific page type among pages connected to a tag I think performance-wise it's a little bit faster to go from the other direction - starting with all pages for the tag and then filter them by page type:
```
  var pagesForTag = TagManager.GetPagesForTag("article", "code");
  var pagesOfPageTypeForTag = pagesForTag.Where(x => x.PageTypeId == pageType.PageTypeId);
```

**Comment by dotnetshadow** [comment]
Thank I forgot the routes.MapMvcAttributeRoutes() thank you so much
