### ISSUE TITLE
Order of Routing Question

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#69]
Hi,

This is more a question than an issue with regards to the order or routing.

Does the CMS inject before calling any defined routes? By this i mean the following

if I have defined a route called *foo/bar*
Does the handler go lookup in the database if a route exists, then if it's not there it will call asp.net controller?
Or does it just use the defined routes in the asp.net application and if it can't find one then it goes into the CMS system?

Option 1
Request made to /foo/bar ->    look up database -> look up asp.net routes

Option 2
Request made to /foo/bar ->  look up asp.net routes ->  look up database

The purpose of the question is if I have defined in the CM
Foo
  - Bar

But I have a controller in my application called Foo and an action called xyz. When I tested it seemd that the CMS would try to look for it and if it didn't find xyz it didn't continue on to find my controller with my xyz.

Is this by design? Also is the database lookup stuff cached or does it check the database on each request?

**Comment by fschultz** [comment]
With both the MVC and WebForms implementation the CMS intercepts the request before ASP.NET does its routing (option 1).

For MVC this means that it happens before the route table is used. The request is first matched against any page in the CMS. If it's a direct match the proper page controller is called. If the request doesn't match a page but part of a page it's tested to see if it's a page using page extension, if not it's assumed to be an action on the last page controller matching the pattern (in your example the page "Foo").
If no match was made the request is passed on to the routing table lookup and the standard ASP.NET MVC behaviour.
The site index is kept in memory so there's no trip to the database for any page lookup (this goes for all; URL lookups, getting pages and children etc).
The page properties are also cached but in a separate way. While the site index never expires from cache, properties can in order to release memory.

**Comment by EdSF** [comment]
This is actually one of my _personal_ favorites about KalikoCMS  - re: it doesn't _impose_ nor tries to _"take over"_. :+1:

**Comment by dotnetshadow** [comment]
Excellent appreciate the response, good work with the caching side of things.
Hopefully with the new ASP.NET 5 pipleline things will work the same
