### ISSUE TITLE
Trailing Slash for pages

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#78]
Hi there,

I was wondering if there is a way to make sure that pages don't end in "/"

i.e. I don't mind if I have articles/apples/ (i.e. category / sections)

But I would like for pages to have no trailing slash currently it looks like everything has a slash at the end of it?
articles/apples/ page-about-articles

Currently it displays as and looks like a category
articles/apples/ page-about-articles/

**Comment by fschultz** [comment]
Currently there's no built in way to switch to URLs without a trailing slash. This is due to how the CMS stores the URLs in the in-memory site index. A site wide settings flag for this could be added but would require extensive testing since it affects page lookup and routing (this would affect all page URLs).

The easiest way would be to TrimEnd the URLs since the CMS will serve requests for ../page-about-articles as well as ../page-about-articles/

**Comment by dotnetshadow** [comment]
Thanks for that, I guess I can use a url rewrite rule to handle the situation
