### ISSUE TITLE
SSO capabilities

### ISSUE THREAD

**Issue by Mukesh-Joshi** [KalikoCMS/KalikoCMS.Core#85]
Hello,

I am completely new to CMS world and I was able to understand it but I have a rather unique problem to implement.
I was not able to find any information if Kaliko has SSO (single sign-on capabilities). If it's there can somebody provide me any demo sites or example through which I can understand it ?

My requirement is to have multiple instances of sites created through Kaliko to have SSO capabilities in between them.

Thanks

**Comment by fschultz** [comment]
Hello,
The ASP.NET Identity-based provider offered with Kaliko CMS has no built-in SSO feature out-of-the-box. However it's possible to use Kaliko CMS with any other ASP.NET security provider, so if you find an authentication system that supports SSO you could use it instead of KalikoCMS.Identity.

I'm a bit too inexperienced with SSO-solutions to really give you a good answer, but one possibility might be looking at using the provided ASP.NET Identity provider together with [Identity Server](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity)

Best regards,
Fredrik
