### ISSUE TITLE
Passwords with either '>' or '<' will fail when logging in

### ISSUE THREAD

**Issue by shanekingsley** [KalikoCMS/KalikoCMS.Core#97]
After setting up Kaliko my admin password was created with a '<' in it. Upon logging in I receive this error:
A potentially dangerous Request.Form value was detected from the client (Password = "PASSWORD" ).

**Comment by fschultz** [comment]
This is due to the default ASP.NET request validation which prevents posting potentially dangerous content. You can either turn this off on a global level, but better would be to make the changes where needed. By setting the **ValidateRequest** attribute to false on the active page:

```
<%@ Page Language="C#" ValidateRequest="false" AutoEventWireup="true" UnobtrusiveValidationMode="None" CodeBehind="Login.aspx.cs" Inherits="DemoSite.Login" %>
```

Hope that helps! Here's some [more information about the request validation](https://msdn.microsoft.com/en-us/library/hh882339(v=vs.110).aspx).
